<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="content-type">
    <title>Καφέ &amp; Εστιατόριο | Μουσείο Ακρόπολης</title>
    <link rel="shortcut icon" href="http://www.theacropolismuseum.gr/sites/all/themes/corporateclean/favicon.ico">
    <link type="text/css" rel="stylesheet" href="http://www.theacropolismuseum.gr/sites/default/files/css/css_nO0hyfSM2Pjy_z58WTHqKvkICvMG_riNF_SC6IDaHEk.css" media="all">
    <link type="text/css" rel="stylesheet" href="http://www.theacropolismuseum.gr/sites/default/files/css/css_GZFAXrM563q94vw50Qx-nDUksio8P9XzYMg_jIRpzQs.css" media="all">
  </head>
  <body>
    <div id="header">
      <div id="header-inside">
        <div id="header-inside-left"> <a href="/~cntouka/acropolis"

            title="Αρχική"><img src="http://www.theacropolismuseum.gr/sites/default/files/logo_el.png"

              alt="Αρχική"></a><br>
        </div>
      </div>
      <div id="header-bottom">
        <div id="title-section">
          <h1>Καφέ &amp; Εστιατόριο</h1>
        </div>
      </div>
    </div>
    <div id="content">
